# Generated by Django 2.2.19 on 2024-05-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_score_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='created_at',
            new_name='data',
        ),
    ]
