# Generated by Django 2.2.19 on 2024-05-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240509_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='dish_name',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
