# Generated by Django 2.2.19 on 2024-05-09 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20240510_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='name',
            field=models.CharField(blank=True, default='Всё подряд.', max_length=100, null=True),
        ),
    ]
