# Generated by Django 2.2.19 on 2024-05-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tabel',
        ),
    ]
